# -*- coding: utf-8 -*-
"""Student Data Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAW5XXQKBoTIJQC4tQYXAF9kiRqwdCWC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dfs=pd.read_csv('/content/student_data.csv')
dfs

dfs.info()

dfs['EthnicGroup ']=dfs['EthnicGroup'].fillna(0)

dfs.dropna(inplace=True)
dfs.info()

dfs

dfs['TestPrep']=dfs['TestPrep'].ffill()
dfs

dfs.info()

dfs.drop('Unnamed: 0',axis=1,inplace=True)
dfs

dfs.reset_index(inplace=True)
dfs

dfs.drop_duplicates(inplace=True)
dfs

dfs.drop('index',axis=1,inplace=True)
dfs

dfs.columns

dfs['Average Score']=dfs[['MathScore','ReadingScore','WritingScore']].mean(axis=1)
dfs

plt.figure(figsize=(15,15), facecolor='lightblue')
plt.gcf().suptitle('Student Performance Dashboard', fontsize=30, color='black', y=1.0)


plt.subplot(3,3,1)
a = sns.countplot(x='Gender', data=dfs, color='red')
plt.title('Gender Count', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i)
plt.gca().set_facecolor('y')



plt.subplot(3,3,2)
gc = dfs['Gender'].value_counts()
plt.pie(gc, labels=gc.index, autopct='%1.2f%%',colors=['orange','red','cyan','lightyellow','purple','brown','lightgreen'],
        shadow=True, textprops={'fontsize':10,'color':'black'}, pctdistance=0.7)
plt.title('Gender Percentage', color='black', fontsize=15)
plt.gca().set_facecolor('y')



plt.subplot(3,3,3)
avg_gender = dfs.groupby('Gender', as_index=False)['Average Score'].mean()
a = sns.barplot(x='Gender', y='Average Score', data=avg_gender,edgecolor='black', hue='Gender', palette='Set1')
plt.title('Gender vs Avg Score', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i, fmt='%.1f')
plt.gca().set_facecolor('y')
plt.tight_layout()




plt.subplot(3,3,4)
a=sns.countplot(x='ParentEduc', data=dfs,color='pink')
plt.title('Parent Education vs Avg Score', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i, fmt='%.1f')
plt.xticks(rotation=45)
plt.gca().set_facecolor('y')
plt.tight_layout()




plt.subplot(3,3,5)
f=dfs['EthnicGroup'].value_counts()
plt.pie(f,labels=f.index,autopct='%0.f%%',colors=['orange','red','cyan','lightyellow','purple','brown','lightgreen'],shadow=True,textprops={'fontsize':10,'color':'black'},pctdistance=0.7)
plt.title('EthnicGroup percentage',color='black',fontsize=15)
plt.gca().set_facecolor('y')
plt.tight_layout()




plt.subplot(3,3,6)
sum_prep = dfs.groupby('TestPrep', as_index=False)['Average Score'].mean()
a = sns.barplot(x='TestPrep', y='Average Score', data=sum_prep,edgecolor='black', hue='TestPrep', palette='Reds')
plt.title('Test Preparation vs Avg Score', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i, fmt='%.1f')
plt.gca().set_facecolor('y')
plt.tight_layout()




plt.subplot(3,3,7)
sum_study = dfs.groupby('WklyStudyHours', as_index=False)['Average Score'].mean()
a = sns.barplot(x='WklyStudyHours', y='Average Score', data=sum_study,edgecolor='black', hue='WklyStudyHours', palette='coolwarm')
plt.title('Study Hours vs Avg Score', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i, fmt='%.1f')
plt.gca().set_facecolor('y')
plt.tight_layout()




plt.subplot(3,3,8)
a = sns.countplot(x='TransportMeans', data=dfs,color='pink')
plt.title('Transport Means Count', color='black', fontsize=15)
for i in a.containers:
    a.bar_label(i)
plt.xticks(rotation=45)
plt.gca().set_facecolor('y')
plt.tight_layout()



plt.subplot(3,3,9)
sns.heatmap(dfs[['MathScore','ReadingScore','WritingScore','Average Score']].corr(),annot=True, cmap='coolwarm')
plt.title('Score Correlation Heatmap', color='black', fontsize=15)
plt.gca().set_facecolor('y')
plt.tight_layout()

plt.show()

"""Student Performance Conclusions:


1.From the first plot, we can see that the number of female students is higher compared to male students.

2.The second plot shows that the percentage of female students is greater than that of male students.

3.In the third plot, the average score of female students is higher than that of male students.

4.The fourth plot indicates that students whose parents have higher education levels score better compared to others.

5.From the fifth plot, we observe that students with standard lunch perform better than those with free/reduced lunch.

6.The sixth plot highlights that students who completed test preparation achieve higher scores compared to those who did not.

7.In the seventh plot, we can see that students who study more hours per week score higher on average.

8.The eighth plot shows that most students use the school bus as their main transport compared to private means.

9.Finally, the ninth plot confirms that Math, Reading, and Writing scores are strongly correlated with each other.
"""